/**
 * Alias Types for PI-SPI
 *
 * The PI-SPI platform supports different types of account aliases:
 *
 * - **SHID**: A randomly generated 36-character unique payment address (UUID format).
 *   Generated by the system when created. Available for all client types (P, C, B, G).
 *   Example: `8b1b2499-3e50-435b-b757-ac7a83d8aa7f`
 *
 * - **MCOD**: Merchant code identifier for USSD payment support.
 *   Available for business clients only (C, B, G). Format: alphanumeric code.
 *   Example: `SNF00_2E4TY`
 *
 * - **MBNO**: Mobile phone number alias.
 *   Available for individual clients (P) only. Format: phone number.
 *   Example: `+221771234567`
 *
 * **Client Type Restrictions:**
 * - Type P (Individuals): Can create MBNO and SHID aliases
 * - Types C, B, G (Businesses): Can create SHID and MCOD aliases
 *
 * **Limits:**
 * - Default limit: 20 aliases per account
 * - Limit can be increased based on client needs
 */

/**
 * Alias type values as defined in the PI-SPI API specification
 */
export const AliasType = {
  /**
   * SHID - System-generated unique payment address (UUID format, 36 characters)
   * Available for all client types: P, C, B, G
   */
  SHID: 'SHID',

  /**
   * MCOD - Merchant code for USSD payment support
   * Available for business clients only: C, B, G
   */
  MCOD: 'MCOD',

  /**
   * MBNO - Mobile phone number alias
   * Available for individual clients only: P
   */
  MBNO: 'MBNO',
} as const;

/**
 * Type representing a valid alias type
 */
export type AliasType = (typeof AliasType)[keyof typeof AliasType];

/**
 * Valid alias types as a tuple for runtime validation
 */
export const ALIAS_TYPES = [AliasType.SHID, AliasType.MCOD, AliasType.MBNO] as const;

/**
 * Check if a string is a valid alias type
 */
export function isValidAliasType(value: string): value is AliasType {
  return ALIAS_TYPES.includes(value as AliasType);
}

/**
 * Get available alias types for a client type
 *
 * @param clientType - Client type: 'P' (Individual), 'C' (Merchant), 'B' (Business), 'G' (Government)
 * @returns Array of available alias types for the client type
 */
export function getAvailableAliasTypes(clientType: 'P' | 'C' | 'B' | 'G'): AliasType[] {
  switch (clientType) {
    case 'P':
      return [AliasType.MBNO, AliasType.SHID];
    case 'C':
    case 'B':
    case 'G':
      return [AliasType.SHID, AliasType.MCOD];
    default:
      return [];
  }
}
